# Generated by Django 4.2.9 on 2024-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='modified_at',
        ),
    ]
